# Generated by Django 5.0.1 on 2024-04-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyQuestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], default='text', max_length=8),
        ),
    ]
