# Generated by Django 5.0.1 on 2024-04-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyQuestions', '0003_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
